name: Deploy to Vercel (Alternative)

# This workflow deploys to Vercel where API routes work
# To use this deployment method:
# 1. Install Vercel CLI: npm i -g vercel
# 2. Connect your repository to Vercel
# 3. Set environment variables in Vercel dashboard
# 4. Enable this workflow by uncommenting the 'on' section

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          CONTACT_PASS: ${{ secrets.CONTACT_PASS }}
          CONTACT_RECEIVER: ${{ secrets.CONTACT_RECEIVER }}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./